# Generated by Django 3.2.9 on 2022-11-24 15:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_post_name', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_gender', models.CharField(max_length=10)),
                ('user_avatar', models.ImageField(upload_to='')),
                ('user_cv', models.FileField(upload_to='')),
                ('user_category', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Вакансии',
                'db_table': 'Users',
            },
        ),
    ]
