# Generated by Django 3.2.9 on 2022-11-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Userss',
        ),
    ]
