# Generated by Django 3.2.9 on 2022-11-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_users_userss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userss',
            name='user_avatar',
            field=models.ImageField(upload_to='main/images/'),
        ),
        migrations.AlterField(
            model_name='userss',
            name='user_cv',
            field=models.FileField(upload_to='main/documents/'),
        ),
    ]
