# Generated by Django 3.2.9 on 2022-11-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_userss_user_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userss',
            name='user_login',
            field=models.CharField(default=444, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userss',
            name='user_password',
            field=models.CharField(default=346, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userss',
            name='user_name',
            field=models.CharField(max_length=150),
        ),
    ]
