# Generated by Django 3.2.9 on 2022-11-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20221125_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='userss',
            name='user_age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
