# Generated by Django 3.2.9 on 2022-11-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userss_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userss',
            name='user_age',
            field=models.CharField(max_length=50),
        ),
    ]
